### PR TITLE
Profile finder UI bug

### PR DESCRIPTION
**Pull request by Rick0317**
I added a back to menu button for ProfilFinderUI when there is no matching

### CODE REVIEW

**Review by a11309 — APPROVED** [review]
Thank you for fixing this! I think Amelia has fixed this, but she just did not make a pull request yet.

**Comment by am3lia-git** [comment]
I don't think this is necessary, when there is no matches, the UI just automatically closes and opens main

**Comment by Rick0317** [comment]
Right, I deleted the button
Because of the MainUI configuration, we need to create an instance of it and call show method. Otherwise, it won't launch MainUI
I modified that part.

**Review by am3lia-git — APPROVED** [review]
okay, this now makes sense to me, thanks Rick for fixing this bug.

**Comment by Rick0317** [comment]
Everything included in the newest pull request

**Pull request closed without merging**
